name: Build Dev build

on:
  #every branch...
  push:
  pull_request:

jobs:
  build-dev:
    name: Build Dev Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Debug

  deploy-to-page:
    name: Deploy WASM
    needs: build-dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: StudyGuide
      url: https://studyguide.pages.dev/

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: StudyGuide-WASM
          path: WASM-Release

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: WASM-Release
